spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 5GB
logging:
  level:
    root: INFO
    com.ceilbhin.stamper: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
font:
  defaultFont: 